version: '3.8'
services:
  web:
    build: .
    ports:
      - "8899:8899"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=1
    command: python game_server.py