apiVersion: apps/v1
kind: Deployment
metadata:
  name: semantle-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: semantle-backend
  template:
    metadata:
      labels:
        app: semantle-backend
    spec:
      containers:
      - name: backend
        image: semantle-backend:latest
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"