apiVersion: apps/v1
kind: Deployment
metadata:
  name: semantle-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: semantle-frontend
  template:
    metadata:
      labels:
        app: semantle-frontend
    spec:
      containers:
      - name: frontend
        image: semantle-frontend:latest
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"