apiVersion: v1
kind: ConfigMap
metadata:
  name: word-game-config
data:
  FLASK_ENV: "production"
  FLASK_APP: "game_server.py"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  MAX_PLAYERS: "2"
  DEBUG: "false"