apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-server-deployment
  labels:
    app: game-server
spec:
  replicas: 2  # Pod 복제 개수 (스케일링을 위해 2개로 설정)
  selector:
    matchLabels:
      app: game-server
  template:
    metadata:
      labels:
        app: game-server
    spec:
      containers:
        - name: flask-app
          image: your-dockerhub-username/flask-app:latest # 이미지 이름 수정
          ports:
            - containerPort: 5000
          env:
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379
