apiVersion: v1
kind: Service
metadata:
  name: game-server-service
spec:
  selector:
    app: game-server
  ports:
    - protocol: TCP
      port: 80         # 외부에 노출될 포트
      targetPort: 5000 # Flask 컨테이너의 포트
  type: LoadBalancer  # 외부에서 접근 가능하도록 설정
