apiVersion: v1
kind: Service
metadata:
  name: flask-service
  annotations:
    cloud.google.com/load-balancer-type: "External"
spec:
  selector:
    app: flask-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30000
    - name: websocket
      protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30001
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
